import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const HIDDEN_HEADER_FOOTER_SIDE: string[] = ["/login"];
  const isHiddenHeaderFooterSide: boolean = HIDDEN_HEADER_FOOTER_SIDE.includes(
    location.pathname
  );

  return (
    <html lang="ko">
      <body className={inter.className}>
        {!isHiddenHeaderFooterSide && <header />}
        {children}
      </body>
    </html>
  );
}
